/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Status: Status;
        /** @enum {number} */
        Priority: Priority;
        Item: {
            name?: string;
            status?: components["schemas"]["Status"];
            priority?: components["schemas"]["Priority"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Item = components['schemas']['Item'];
export type $defs = Record<string, never>;
export enum Status {
    active = "active",
    inactive = "inactive",
    pending = "pending"
}
export enum Priority {
    Value1 = 1,
    Value2 = 2,
    Value3 = 3
}
export type operations = Record<string, never>;
