type: object

properties:
  config:
    anyOf:
      - $ref: './advanced_config/mysql_advanced_config.yml'
      - $ref: './advanced_config/postgres_advanced_config.yml'
      - $ref: './advanced_config/redis_advanced_config.yml'
      - $ref: './advanced_config/mongo_advanced_config.yml'
      - $ref: './advanced_config/kafka_advanced_config.yml'
      - $ref: './advanced_config/opensearch_advanced_config.yml'
