packages:
  - docs
  - packages/**

catalog:
  execa: ^9.6.0
  typescript: ^5.9.2
  vite: ^7.1.5

ignoredBuiltDependencies:
  - "@swc/core"
  - esbuild
  - msw
  - sharp
  - svelte-preprocess

onlyBuiltDependencies:
  - "@biomejs/biome"
