operationId: kubernetes_get_kubeconfig

summary: Retrieve the kubeconfig for a Kubernetes Cluster

description: |
  This endpoint returns a kubeconfig file in YAML format. It can be used to
  connect to and administer the cluster using the Kubernetes command line tool,
  `kubectl`, or other programs supporting kubeconfig files (e.g., client libraries).

  The resulting kubeconfig file uses token-based authentication for clusters
  supporting it, and certificate-based authentication otherwise. For a list of
  supported versions and more information, see "[How to Connect to a DigitalOcean
  Kubernetes Cluster](https://docs.digitalocean.com/products/kubernetes/how-to/connect-to-cluster/)".

  To retrieve a kubeconfig file for use with a Kubernetes cluster, send a GET
  request to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/kubeconfig`.

  Clusters supporting token-based authentication may define an expiration by
  passing a duration in seconds as a query parameter to
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/kubeconfig?expiry_seconds=$DURATION_IN_SECONDS`.
  If not set or 0, then the token will have a 7 day expiry. The query parameter
  has no impact in certificate-based authentication.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'
  - $ref: 'parameters.yml#/kubernetes_expiry_seconds'

responses:
  '200':
    $ref: 'responses/kubeconfig.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_get_kubeconfig.yml'
  - $ref: 'examples/go/kubernetes_get_kubeconfig.yml'
  - $ref: 'examples/ruby/kubernetes_get_kubeconfig.yml'
  - $ref: 'examples/python/kubernetes_get_kubeconfig.yml'

security:
  - bearer_auth:
    - 'kubernetes:access_cluster'
