operationId: kubernetes_update_cluster

summary: Update a Kubernetes Cluster

description: |
  To update a Kubernetes cluster, send a PUT request to
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID` and specify one or more of the
  attributes below.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'

requestBody:
  required: true

  content:
    application/json:
      schema:
        $ref: 'models/cluster_update.yml'

responses:
  '202':
    $ref: 'responses/updated_cluster.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_update_cluster.yml'
  - $ref: 'examples/go/kubernetes_update_cluster.yml'
  - $ref: 'examples/ruby/kubernetes_update_cluster.yml'
  - $ref: 'examples/python/kubernetes_update_cluster.yml'

security:
  - bearer_auth:
    - 'kubernetes:update'
