operationId: kubernetes_get_cluster

summary: Retrieve an Existing Kubernetes Cluster

description: |
  To show information about an existing Kubernetes cluster, send a GET request
  to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID`.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'

responses:
  '200':
    $ref: 'responses/existing_cluster.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_get_cluster.yml'
  - $ref: 'examples/go/kubernetes_get_cluster.yml'
  - $ref: 'examples/ruby/kubernetes_get_cluster.yml'
  - $ref: 'examples/python/kubernetes_get_cluster.yml'

security:
  - bearer_auth:
    - 'kubernetes:read'
