operationId: kubernetes_get_availableUpgrades

summary: Retrieve Available Upgrades for an Existing Kubernetes Cluster

description: |
  To determine whether a cluster can be upgraded, and the versions to which it
  can be upgraded, send a GET request to
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/upgrades`.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'

responses:
  '200':
    $ref: 'responses/available_upgrades.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_get_availableUpgrades.yml'
  - $ref: 'examples/go/kubernetes_get_availableUpgrades.yml'
  - $ref: 'examples/python/kubernetes_get_availableUpgrades.yml'

security:
  - bearer_auth:
    - 'kubernetes:read'
