operationId: kubernetes_list_clusters

summary: List All Kubernetes Clusters

description: |
  To list all of the Kubernetes clusters on your account, send a GET request
  to `/v2/kubernetes/clusters`.

tags:
  - Kubernetes

parameters:
  - $ref: '../../shared/parameters.yml#/per_page'
  - $ref: '../../shared/parameters.yml#/page'

responses:
  '200':
    $ref: 'responses/all_clusters.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_list_clusters.yml'
  - $ref: 'examples/go/kubernetes_list_clusters.yml'
  - $ref: 'examples/ruby/kubernetes_list_clusters.yml'
  - $ref: 'examples/python/kubernetes_list_clusters.yml'

security:
  - bearer_auth:
    - 'kubernetes:read'
