operationId: kubernetes_get_clusterUser

summary: Retrieve User Information for a Kubernetes Cluster

description: |
  To show information the user associated with a Kubernetes cluster, send a GET
  request to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/user`.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'

responses:
  '200':
    $ref: 'responses/cluster_user.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_get_clusterUser.yml'
  - $ref: 'examples/python/kubernetes_get_clusterUser.yml'

security:
  - bearer_auth:
    - 'kubernetes:read'
