type: object

properties:
  default_read_concern:
    description: >-
      Specifies the default consistency behavior of reads from the database. Data that is returned from the query with may
      or may not have been acknowledged by all nodes in the replicaset depending on this value. 
      Learn more [here](https://www.mongodb.com/docs/manual/reference/read-concern/).
    type: string
    enum: [local, available, majority]
    default: local
    example: local
  default_write_concern:
    description: >-
      Describes the level of acknowledgment requested from MongoDB for write operations clusters. This field can set to either `majority`
      or a number `0...n` which will describe the number of nodes that must acknowledge the write operation before it is fully accepted.
      Setting to `0` will request no acknowledgement of the write operation. 
      Learn more [here](https://www.mongodb.com/docs/manual/reference/write-concern/).
    type: string
    default: majority
    example: majority
  transaction_lifetime_limit_seconds:
    description: >-
        Specifies the lifetime of multi-document transactions. Transactions that exceed this limit are considered expired and will be 
        aborted by a periodic cleanup process. The cleanup process runs every `transactionLifetimeLimitSeconds/2 seconds` or at least 
        once every 60 seconds. *Changing this parameter will lead to a restart of the MongoDB service.*
        Learn more [here](https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.transactionLifetimeLimitSeconds).
    type: integer
    minimum: 1
    default: 60
    example: 100
  slow_op_threshold_ms:
    description: >-
        Operations that run for longer than this threshold are considered slow which are then recorded to the diagnostic logs. 
        Higher log levels (verbosity) will record all operations regardless of this threshold on the primary node. 
        *Changing this parameter will lead to a restart of the MongoDB service.*
        Learn more [here](https://www.mongodb.com/docs/manual/reference/configuration-options/#mongodb-setting-operationProfiling.slowOpThresholdMs).
    type: integer
    minimum: 0
    default: 100
    example: 200
  verbosity:
    description: >-
        The log message verbosity level. The verbosity level determines the amount of Informational and Debug messages MongoDB outputs.
        0 includes informational messages while 1...5 increases the level to include debug messages.
        *Changing this parameter will lead to a restart of the MongoDB service.*
        Learn more [here](https://www.mongodb.com/docs/manual/reference/configuration-options/#mongodb-setting-systemLog.verbosity).
    type: integer
    minimum: 0
    maximum: 5
    default: 0
    example: 3