import openapiTS from "../src/index";

describe("allow empty definitions", () => {
  it("allow empty definitions", async () => {
    const schema = {
      swagger: "2.0",
      paths: {
        "/pet": {
          post: {
            description: "",
            operationId: "addPet",
            parameters: [
              {
                in: "body",
                name: "body",
                description: "Pet object that needs to be added to the store",
                required: true,
                schema: {
                  $ref: 'definitions["Pet"]',
                },
              },
            ],
            responses: {
              405: {
                description: "Invalid input",
              },
            },
          },
        },
      },
    };

    expect(await openapiTS(schema as any, { version: 2 })).toBe(`/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/pet": {
    post: operations["addPet"];
  };
}

export interface operations {
  addPet: {
    parameters: {
      body: {
        /** Pet object that needs to be added to the store */
        body: definitions["Pet"];
      };
    };
    responses: {
      /** Invalid input */
      405: unknown;
    };
  };
}

export interface external {}
`);

    expect(await openapiTS(schema as any, { immutableTypes: true, version: 2 })).toBe(`/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly "/pet": {
    readonly post: operations["addPet"];
  };
}

export interface operations {
  readonly addPet: {
    readonly parameters: {
      readonly body: {
        /** Pet object that needs to be added to the store */
        readonly body: definitions["Pet"];
      };
    };
    readonly responses: {
      /** Invalid input */
      readonly 405: unknown;
    };
  };
}

export interface external {}
`);
  });
});
