import { default as openapiTS } from "../src/index";

describe("formatter", () => {
  it("basic", () => {
    const schema = {
      openapi: "3.0.1",
      components: {
        schemas: {
          date: {
            type: "string",
            format: "date-time",
          },
        },
      },
    };
    expect(
      openapiTS(schema, {
        formatter(schemaObj) {
          if (schemaObj.format === "date-time") {
            return "Date";
          }
          return;
        },
        version: 3,
      })
    ).toBe(`/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    date: Date;
  };
}

export interface operations {}
`);
  });
});
