import openapiTS from "../src/index";

describe("rawSchema", () => {
  it("v2", () => {
    const v2schema = {
      User: {
        type: "object",
        properties: {
          name: { type: "string", description: "user name" },
          email: { type: "string", description: "user email" },
        },
        required: ["name", "email"],
      },
    };

    expect(
      openapiTS(v2schema, {
        rawSchema: true,
        version: 2,
      })
    ).toBe(`/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface definitions {
  User: {
    /** user name */
    name: string;
    /** user email */
    email: string;
  };
}\n`);

    expect(
      openapiTS(v2schema, {
        immutableTypes: true,
        rawSchema: true,
        version: 2,
      })
    ).toBe(`/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface definitions {
  readonly User: {
    /** user name */
    readonly name: string;
    /** user email */
    readonly email: string;
  };
}\n`);
  });

  it("v3", () => {
    const v3schema = {
      User: {
        type: "object",
        properties: {
          name: { type: "string", description: "user name" },
          email: { type: "string", description: "user email" },
        },
        required: ["name", "email"],
      },
    };

    expect(
      openapiTS(v3schema, {
        rawSchema: true,
        version: 3,
      })
    ).toBe(`/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface schemas {
  User: {
    /** user name */
    name: string;
    /** user email */
    email: string;
  };
}\n`);

    expect(
      openapiTS(v3schema, {
        immutableTypes: true,
        rawSchema: true,
        version: 3,
      })
    ).toBe(`/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface schemas {
  readonly User: {
    /** user name */
    readonly name: string;
    /** user email */
    readonly email: string;
  };
}\n`);
  });
});
