/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/test': {
    get: {
      parameters: {
        query: {
          search: string
        }
      }
      responses: {
        200: unknown
      }
    }
  }
}

export type definitions = {
  TestSchema: {
    /**
     * @default false
     * @example false
     */
    isEnabled?: boolean
    /**
     * @default 0
     * @example 0
     */
    count?: number
  }
}

export type operations = {}

export type external = {}
