/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly '/test': {
    readonly get: {
      readonly parameters: {
        readonly query: {
          readonly search: string
        }
      }
      readonly responses: {
        readonly 200: unknown
      }
    }
  }
}

export interface definitions {
  readonly TestSchema: {
    /**
     * @default false
     * @example false
     */
    readonly isEnabled?: boolean
    /**
     * @default 0
     * @example 0
     */
    readonly count?: number
  }
}

export interface operations {}

export interface external {}
