/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/pet': {
    post: operations['addPet']
  }
}

export interface definitions {
  Pet: {
    /** Format: int64 */
    id?: number
    /** @example doggie */
    name: string
  }
}

export interface operations {
  addPet: {
    parameters: {
      body: {
        body: {
          name?: definitions['Pet']['name']
        }
      }
    }
    responses: {
      200: unknown
    }
  }
}

export interface external {}
