/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/cats': {
    post: {
      responses: {
        200: {
          content: {
            'application/json': {
              id: string
              name: string
              colors: (
                | string[]
                | {
                    id: string
                    name: string
                  }[]
              ) & { [key: string]: unknown }
            }
          }
        }
      }
    }
  }
}

export interface components {}

export interface operations {}

export interface external {}
