/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/test': {
    get: {
      responses: {
        /** A list of types. */
        200: unknown
      }
    }
  }
}

export interface components {
  schemas: {
    /** @constant */
    TypeA: { hello: 'world' }
    /** @constant */
    TypeB: ['content']
  }
}

export interface operations {}

export interface external {}
