/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly '/test': {
    readonly get: {
      readonly responses: {
        /** A list of types. */
        readonly 200: unknown
      }
    }
  }
}

export interface components {
  readonly schemas: {
    /** @constant */
    readonly TypeA: { hello: 'world' }
    /** @constant */
    readonly TypeB: ['content']
  }
}

export interface operations {}

export interface external {}
