/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/v1/getUser2': {
    /** UserController.getUser2 */
    get: operations['UserController.getUser2.DjHhjSamaD']
  }
}

export type components = {
  schemas: {
    IUserWithId: components['schemas']['Partial<Pick<IUser,"id">>'] | string
    'Partial<Pick<IUser,"id">>': {
      id?: number
    }
    IUserWithName: {
      name: string
    }
    IUser: {
      id: number
      name?: string
    }
  }
}

export type operations = {
  /** UserController.getUser2 */
  'UserController.getUser2.DjHhjSamaD': {
    parameters: {
      query: {
        param1?: number
        param2?: string | components['schemas']['IUserWithId']
        param3?: string | components['schemas']['IUserWithName']
      }
    }
    responses: {
      /** Successful response */
      200: {
        content: {
          'application/json': unknown
        }
      }
    }
  }
}

export type external = {}
