/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/test": {
    get: {
      responses: {
        /** A list of types. */
        200: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    /** @description Enum with null and nullable */
    MyType: {
      myField?: ("foo" | "bar") | null;
    } & { [key: string]: unknown };
    /** @description Enum with null */
    MyTypeNotNullable: {
      myField?: "foo" | "bar" | null;
    } & { [key: string]: unknown };
    /** @description Enum with null */
    MyTypeNotNullableNotNull: {
      myField?: "foo" | "bar";
    } & { [key: string]: unknown };
    /** @description Enum with null */
    MyTypeMixed: {
      myField?: "foo" | 2 | false | null;
    } & { [key: string]: unknown };
  };
}

export interface operations {}

export interface external {}
