/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/test': {
    get: {
      responses: {
        /** A list of types. */
        200: unknown
      }
    }
  }
}

export interface components {
  schemas: {
    /** @description Enum with null and nullable */
    Example: {
      emptyAllOf?: { [key: string]: unknown }
      emptyOneOf?: undefined & { [key: string]: unknown }
      emptyAnyOf?: { [key: string]: unknown }
    } & { [key: string]: unknown }
  }
}

export interface operations {}

export interface external {}
