/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly '/test': {
    readonly get: {
      readonly responses: {
        /** A list of types. */
        readonly 200: unknown
      }
    }
  }
}

export interface components {
  readonly schemas: {
    /** @description Enum with null and nullable */
    readonly Example: {
      readonly emptyAllOf?: undefined
      readonly emptyOneOf?: undefined
      readonly emptyAnyOf?: undefined
    }
  }
}

export interface operations {}

export interface external {}
