description: A JSON object with a key of `config`.

headers:
  ratelimit-limit:
    $ref: '../../../shared/headers.yml#/ratelimit-limit'
  ratelimit-remaining:
    $ref: '../../../shared/headers.yml#/ratelimit-remaining'
  ratelimit-reset:
    $ref: '../../../shared/headers.yml#/ratelimit-reset'

content:
  application/json:
    schema:
      type: object
      properties:
        config:
          anyOf:
            - $ref: '../models/advanced_config/mysql_advanced_config.yml'
            - $ref: '../models/advanced_config/postgres_advanced_config.yml'
            - $ref: '../models/advanced_config/redis_advanced_config.yml'
            - $ref: '../models/advanced_config/kafka_advanced_config.yml'
            - $ref: '../models/advanced_config/opensearch_advanced_config.yml'
            - $ref: '../models/advanced_config/mongo_advanced_config.yml'
      required:
        - config
    example:
      config:
        sql_mode: ANSI,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_ALL_TABLES
        sql_require_primary_key: true
