type: object

properties:
  target_number_instances:
    title: static config
    type: integer
    example: 3
    description: Fixed number of instances in an autoscale pool.
    minimum: 1
    maximum: 1000

required:
  - target_number_instances
