operationId: databases_get_config

summary: Retrieve an Existing Database Cluster Configuration

description: |
  Shows configuration parameters for an existing database cluster by sending a GET request to
  `/v2/databases/$DATABASE_ID/config`.
  The response is a JSON object with a `config` key, which is set to an object
  containing any database configuration parameters.
tags:
  - Databases

parameters:
  - $ref: 'parameters.yml#/database_cluster_uuid'

responses:
  '200':
    $ref: 'responses/database_config.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/databases_get_config.yml'
  - $ref: 'examples/python/databases_get_config.yml'

security:
  - bearer_auth:
    - 'database:read'
