database_cluster_uuid:
  in: path
  name: database_cluster_uuid
  description: A unique identifier for a database cluster.
  required: true
  example: 9cc10173-e9ea-4176-9dbc-a4cee4c4ff30
  schema:
    type: string
    format: uuid

database_name:
  in: path
  name: database_name
  description: The name of the database.
  required: true
  example: alpha
  schema:
    type: string

replica_name:
  in: path
  name: replica_name
  description: The name of the database replica.
  required: true
  example: read-nyc3-01
  schema:
    type: string

username:
  in: path
  name: username
  description: The name of the database user.
  required: true
  example: app-01
  schema:
    type: string

tag_name:
  in: query
  name: tag_name
  description: Limits the results to database clusters with a specific tag.
  required: false
  example: production
  schema:
    type: string

pool_name:
  in: path
  name: pool_name
  description: The name used to identify the connection pool.
  required: true
  example: backend-pool
  schema:
    type: string

migration_id:
  in: path
  name: migration_id
  description: A unique identifier assigned to the online migration.
  required: true
  example: 77b28fc8-19ff-11eb-8c9c-c68e24557488
  schema:
    type: string

kafka_topic_name:
  in: path
  name: topic_name
  description: The name used to identify the Kafka topic.
  required: true
  example: customer-events
  schema:
    type: string
