type: object

description: An object specifying forwarding configurations for a Global load balancer.

properties:
  target_protocol:
    type: string
    enum:
      - http
      - https
      - http2
    example: http
    description: The protocol used for forwarding traffic from the load balancer to the 
      target backends. The possible values are `http`, `https` and `http2`.

  target_port:
    type: integer
    example: 80
    description: An integer representing the port on the target backends which the
      load balancer will forward traffic to.

  cdn:
    type: object
    properties:
      is_enabled:
        type: boolean
        example: true
        description: A boolean flag to enable CDN caching.
    description: An object specifying CDN configurations for a Global load balancer.

  region_priorities:
    type: object
    additionalProperties:
      type: integer
    example:
      "nyc1": 1
      "fra1": 2
      "sgp1": 3
    description: A map of region string to an integer priority value indicating preference
      for which regional target a Global load balancer will forward traffic to. A lower
      value indicates a higher priority.

  failover_threshold:
    type: integer
    example: 50
    description: An integer value as a percentage to indicate failure threshold to decide how
      the regional priorities will take effect. A value of `50` would indicate that the Global
      load balancer will choose a lower priority region to forward traffic to once this failure
      threshold has been reached for the higher priority region.
