/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    calendar: {
      dates?: {
        /** Format: date-time */
        start?: Date;
      };
    };
  };
}

export interface operations {}

export interface external {}
