/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    /** Format: date-time */
    date: Date;
  };
}

export interface operations {}

export interface external {}
