/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/test": {
    post: operations["addTest"];
  };
}

export interface definitions {
  /** @description Enum with null and nullable */
  MyType: {
    myField?: ("foo" | "bar") | null;
  };
  /** @description Enum with null */
  MyTypeNotNullable: {
    myField?: "foo" | "bar" | null;
  };
  /** @description Enum with null */
  MyTypeNotNullableNotNull: {
    myField?: "foo" | "bar";
  };
  /** @description Enum with null */
  MyTypeMixed: {
    myField?: "foo" | 2 | false | null;
  };
}

export interface operations {
  addTest: {
    responses: {
      /** OK */
      200: unknown;
    };
  };
}

export interface external {}
