vpc_peering_id:
  in: path
  name: vpc_peering_id
  description: A unique identifier for a VPC peering.
  required: true
  schema:
    type: string
    format: uuid
  example: 5a4981aa-9653-4bd1-bef5-d6bff52042e4
