droplet_id:
  in: query
  name: host_id
  description: The droplet ID.
  example: "17209102"
  required: true
  schema:
    type: string

app_id:
  in: query
  name: app_id
  description: The app UUID.
  example: "2db3c021-15ad-4088-bfe8-99dc972b9cf6"
  required: true
  schema:
    type: string

load_balancer_id:
  in: query
  name: lb_id
  description: A unique identifier for a load balancer.
  required: true
  schema:
    type: string
  example: 4de7ac8b-495b-4884-9a69-1050c6793cd6

app_component:
  in: query
  name: app_component
  description: The app component name.
  example: "sample-application"
  required: false
  schema:
    type: string

network_interface:
  in: query
  name: interface
  description: The network interface.
  required: true
  example: "private"
  schema:
    type: string
    enum:
      - private
      - public
network_direction:
  in: query
  name: direction
  description: The traffic direction.
  required: true
  example: "inbound"
  schema:
    type: string
    enum:
      - inbound
      - outbound
metric_timestamp_start:
  in: query
  name: start
  description: UNIX timestamp to start metric window.
  example: "1620683817"
  required: true
  schema:
    type: string

metric_timestamp_end:
  in: query
  name: end
  description: UNIX timestamp to end metric window.
  example: "1620705417"
  required: true
  schema:
    type: string

alert_uuid:
  in: path
  name: alert_uuid
  description: A unique identifier for an alert policy.
  required: true
  schema:
    type: string
  example: 4de7ac8b-495b-4884-9a69-1050c6793cd6
