operationId: security_update_settings_plan

summary: Update Plan

description: To update CSPM plan coverage, send a PUT request to `/v2/security/settings/plan`.

tags:
  - Security

requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          tier_coverage:
            type: object
            description: Scan coverage for each available plan tier.
            additionalProperties:
              type: object
              properties:
                resources:
                  type: array
                  items:
                    type: string
                  description: The URNs of resources to scan for the tier.
                  default: []
                  example:
                    - do:droplet:fe3a2fd7-903d-46e6-ada3-3e4f285fb89d
                tags:
                  type: array
                  items:
                    type: string
                  description: Resource tags to scan for the tier.
                  default: []
                  example:
                    - production
            example:
              basic:
                resources:
                  - do:droplet:fe3a2fd7-903d-46e6-ada3-3e4f285fb89d
                tags:
                  - production

responses:
  '200':
    $ref: 'responses/tier_coverage.yml'

  '400':
    $ref: '../../shared/responses/bad_request.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/security_settings_plan_update.yml'

security:
  - bearer_auth:
      - 'security:update'
