import path from "path";
import prettier from "prettier";
import { swaggerVersion } from "./utils";
import {
  OpenAPI2,
  OpenAPI2Schemas,
  OpenAPI3,
  OpenAPI3Schemas,
  SwaggerToTSOptions,
} from "./types";
import v2 from "./v2";
import v3 from "./v3";

export const WARNING_MESSAGE = `/**
* This file was auto-generated by openapi-typescript.
* Do not make direct changes to the file.
*/


`;

export default function swaggerToTS(
  schema: OpenAPI2 | OpenAPI2Schemas | OpenAPI3 | OpenAPI3Schemas,
  options?: SwaggerToTSOptions
): string {
  // generate types for V2 and V3
  const version =
    (options && options.version) ||
    swaggerVersion(schema as OpenAPI2 | OpenAPI3);
  let output = `${WARNING_MESSAGE}`;
  switch (version) {
    case 2: {
      output = output.concat(v2(schema as OpenAPI2 | OpenAPI2Schemas, options));
      break;
    }
    case 3: {
      output = output.concat(v3(schema as OpenAPI3 | OpenAPI3Schemas, options));
      break;
    }
  }

  // Prettify output
  let prettierOptions: prettier.Options = { parser: "typescript" };
  if (options && options.prettierConfig) {
    try {
      const userOptions = prettier.resolveConfig.sync(
        path.resolve(process.cwd(), options.prettierConfig)
      );
      prettierOptions = {
        ...prettierOptions,
        ...userOptions,
      };
    } catch (err) {
      console.error(`❌ ${err}`);
    }
  }
  return prettier.format(output, prettierOptions);
}
